### ISSUE TITLE
Cannot export due to missing/unreadable handlebar template file or stylesheet

### ISSUE THREAD

**Issue by indiependente** [karlitos/jsonresume-theme-mocha-responsive#12]
Hi,

When I try to export using `resume-cli`/`kissmyresume` with this command
```bash
resume export -r resume.json -t mocha-responsive dist/resume.pdf
```
I get the following error:
```
Error: The source handlebar template file or the stylesheet could not be read.
    at Object.render (/Users/itff/repos/github.com/indiependente/jsonresume/node_modules/jsonresume-theme-mocha-responsive/index.js:159:9)
    at _default (/usr/local/lib/node_modules/resume-cli/build/render-html.js:52:16)
    at /usr/local/lib/node_modules/resume-cli/build/export-resume.js:107:48
    at createPdf (/usr/local/lib/node_modules/resume-cli/build/export-resume.js:131:5)
    at module.exports (/usr/local/lib/node_modules/resume-cli/build/export-resume.js:44:5)
    at Command.<anonymous> (/usr/local/lib/node_modules/resume-cli/build/main.js:67:5)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at async /usr/local/lib/node_modules/resume-cli/build/main.js:79:3 `createPdf` errored out

Done! Find your new .pdf resume at:
 /Users/itff/repos/github.com/indiependente/jsonresume/dist/resume.pdf
```
The PDF is not generated.

Same happens for HTML exports:
```
resume export -r resume.json -t mocha-responsive dist/index.html
/Users/itff/repos/github.com/indiependente/jsonresume/node_modules/jsonresume-theme-mocha-responsive/index.js:159
		throw new Error('The source handlebar template file or the stylesheet could not be read.');
		      ^

Error: The source handlebar template file or the stylesheet could not be read.
    at Object.render (/Users/itff/repos/github.com/indiependente/jsonresume/node_modules/jsonresume-theme-mocha-responsive/index.js:159:9)
    at _default (/usr/local/lib/node_modules/resume-cli/build/render-html.js:52:16)
    at createHtml (/usr/local/lib/node_modules/resume-cli/build/export-resume.js:84:46)
    at module.exports (/usr/local/lib/node_modules/resume-cli/build/export-resume.js:36:5)
    at Command.<anonymous> (/usr/local/lib/node_modules/resume-cli/build/main.js:67:5)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at async /usr/local/lib/node_modules/resume-cli/build/main.js:79:3
```

Could you please provide help on how to solve this issue?

Thanks.

**Comment by gggiovanny** [comment]
I've got the same problem using _kissmyresume_. With this command:
```
RENDER_MARKDOWN=true kissmyresume build resume/base.json --theme node_modules/jsonresume-theme-mocha-responsive/
```
I've got this error:
```
+++ KissMyResume v0.8.2 +++

Parsing resume file from /mnt/d/Files/Documents/CV/resume/base.json

Succesfully parsed resume in JSON-Resume format.

Export to multiple formats failed! Reason: Error: The source handlebar template file or the stylesheet could not be read.
```

**Comment by bizzinho** [comment]
same for me as for @gggiovanny

**Comment by adriansun1** [comment]
installing fontawesome free in `node_modules/jsonresume-theme-mocha-responsive` fixed it for me. 
```
npm install @fortawesome/fontawesome-free -S
```

this pr would probably fix things https://github.com/karlitos/jsonresume-theme-mocha-responsive/pull/7
